[package]
name = "rett"
version = "0.1.0"
authors = ["Fran√ßois Gindraud <francois.gindraud@gmail.com>"]
description = "Tool to store, manipulate and display relational information"

[dependencies]
rouille = "2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2"
horrorshow = "0.6"
rust-embed = "3"
